### ISSUE TITLE
Error "File Isn't a JSON Array" with example.json

### ISSUE THREAD

**Issue by j842** [p-jackson/grizzly-pass#1]
Using example.json from here:
https://github.com/p-jackson/grizzly-pass/blob/master/example/example.json

on https://grizzly-pass.surge.sh/

I get "File Isn't a JSON Array"

[Tried in Chrome and Opera, the file passes basic JSON lint tools]

**Comment by p-jackson** [comment]
Thanks @j842, my docs got a bit behind my dev work there.

**Comment by j842** [comment]
Nice improvements to the JSON format!
